name: Release Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build binaries
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name confexp main.py

      - name: Archive artifact
        shell: bash
        run: |
          mkdir -p upload
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a upload/confexp-windows.zip dist/confexp.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            zip -j upload/confexp-macos.zip dist/confexp
          else
            zip -j upload/confexp-linux.zip dist/confexp
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: confexp-${{ matrix.os }}
          path: upload/*.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
