name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile --name confexp main.py

      - name: Prepare upload dir
        run: mkdir upload
        shell: bash

      - name: Archive binary (Linux)
        if: runner.os == 'Linux'
        run: zip -j upload/confexp-linux.zip dist/confexp

      - name: Archive binary (macOS)
        if: runner.os == 'macOS'
        run: zip -j upload/confexp-macos.zip dist/confexp

      - name: Archive binary (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path dist\confexp.exe -DestinationPath upload\confexp-windows.zip

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
