name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --clean confexp.spec

      # Archive for Linux
      - name: Archive Linux binary
        if: runner.os == 'Linux'
        run: |
          mkdir -p upload
          BIN_PATH=$(find dist -type f -name "confexp" | head -n 1)
          if [ -z "$BIN_PATH" ]; then
            echo "❌ Binary not found!"
            exit 1
          fi
          zip -j upload/confexp-linux.zip "$BIN_PATH"

      # Archive for macOS
      - name: Archive macOS binary
        if: runner.os == 'macOS'
        run: |
          mkdir -p upload
          BIN_PATH=$(find dist -type f -name "confexp" | head -n 1)
          if [ -z "$BIN_PATH" ]; then
            echo "❌ Binary not found!"
            exit 1
          fi
          zip -j upload/confexp-macos.zip "$BIN_PATH"

      # Archive for Windows
      - name: Archive Windows binary
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path upload | Out-Null
          $exePath = Get-ChildItem -Path dist -Filter "confexp.exe" -Recurse | Select-Object -First 1
          if (-not $exePath) { throw "❌ confexp.exe not found in dist directory" }
          Compress-Archive -Path $exePath.FullName -DestinationPath upload\confexp-windows.zip -Force

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: confexp-${{ runner.os }}
          path: upload/*
